apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: testcert
spec:
  secretName: example-com-tls
  issuerRef:
    name: vault-issuer
  commonName: www.example.com
  dnsNames:
  - www.example.com
